FROM almalinux:9
ENV course="DevOps with AWS" \
    trainer="sivakumar reddy" \
    duration="120HRS"
ARG USERNAME=SIVASAIKUMAR
RUN echo "Hello this is : ${USERNAME}" > /tmp/devops.txt
CMD ["sleep", "100"]